export const AMENITIES = [
  "Bord de l'eau",
  "Piscine intérieure",
  "Piscine extérieure",
  "Ski in / Ski out",
  "Situé sur un resort",
  "Spa",
  "Sauna",
  "Chalet en bois rond",
  "Foyer intérieur au bois",
  "Foyer extérieur (firepit)",
  "BBQ",
  "Table de billard",
  "Babyfoot",
  "Table de ping-pong",
  "Arcades",
  "Jeux de société",
  "Livres et Revues",
  "Gym",
  "Wifi",
  "Espace de travail dédié (télétravail)",
  "Climatisation",
  "Télévision avec câble",
  "Télévision intelligente",
  "Système audio (musique)",
  "Cuisine complète avec vaisselle et chaudrons",
  "Literie et serviettes incluses",
  "Buanderie",
  "Terrasse",
  "Module de jeux pour enfant",
  "Borne de recharge pour véhicule électrique",
] as const;

export const AMENITY_EMOJI: Record<string, string> = {
  "Bord de l'eau":                              "🌊",
  "Piscine intérieure":                         "🏊",
  "Piscine extérieure":                         "🏊",
  "Ski in / Ski out":                           "⛷️",
  "Situé sur un resort":                        "🏔️",
  "Spa":                                        "♨️",
  "Sauna":                                      "🧖",
  "Chalet en bois rond":                        "🪵",
  "Foyer intérieur au bois":                    "🔥",
  "Foyer extérieur (firepit)":                  "🔥",
  "BBQ":                                        "🍖",
  "Table de billard":                           "🎱",
  "Babyfoot":                                   "⚽",
  "Table de ping-pong":                         "🏓",
  "Arcades":                                    "🕹️",
  "Jeux de société":                            "🎲",
  "Livres et Revues":                           "📚",
  "Gym":                                        "💪",
  "Wifi":                                       "📶",
  "Espace de travail dédié (télétravail)":      "💻",
  "Climatisation":                              "❄️",
  "Télévision avec câble":                      "📺",
  "Télévision intelligente":                    "📺",
  "Système audio (musique)":                    "🎵",
  "Cuisine complète avec vaisselle et chaudrons": "🍳",
  "Literie et serviettes incluses":             "🛏️",
  "Buanderie":                                  "👕",
  "Terrasse":                                   "🪑",
  "Module de jeux pour enfant":                 "🛝",
  "Borne de recharge pour véhicule électrique": "⚡",
};
