export const NEARBY_BY_CATEGORY: Record<string, string[]> = {
  "Été": [
    "Glissades d'eau / Parc aquatique",
    "Vélo de montagne",
    "Piste cyclable",
    "Randonnée pédestre",
    "Pêche",
    "Accès à un lac",
    "Accès à un lac avec embarcation à moteur",
    "Plage",
    "Parcours arbre-en-arbre",
    "Tyrolienne",
    "Paintball",
    "Go Kart",
    "Cinéparc",
    "Équitation",
    "Golf",
    "Escalade",
    "Croisière / Excursion nautique",
  ],
  "Hiver": [
    "Ski alpin",
    "Motoneige",
    "Traîneau à chiens",
    "Sentiers de raquettes",
    "Ski de fond",
    "Pêche sur glace",
    "Glissade sur tube",
    "Équitation",
    "Patinage / Hockey extérieur",
    "Fatbike",
  ],
  "4 saisons": [
    "Cabane à sucre",
    "Magasinage (shopping)",
    "Musée",
    "Restaurant / Bistro",
    "Microbrasserie",
    "Spa nordique",
    "Casino",
    "Cinéma",
    "Village touristique",
  ],
};

export const NEARBY_EN: Record<string, string> = {
  "Glissades d'eau / Parc aquatique": "Water slides / Water park",
  "Vélo de montagne": "Mountain biking",
  "Piste cyclable": "Bike path",
  "Randonnée pédestre": "Hiking",
  "Pêche": "Fishing",
  "Accès à un lac": "Lake access",
  "Accès à un lac avec embarcation à moteur": "Lake access with motorboat",
  "Plage": "Beach",
  "Parcours arbre-en-arbre": "Treetop adventure course",
  "Tyrolienne": "Zipline",
  "Paintball": "Paintball",
  "Go Kart": "Go-kart",
  "Cinéparc": "Drive-in movie theatre",
  "Équitation": "Horseback riding",
  "Golf": "Golf",
  "Escalade": "Rock climbing",
  "Croisière / Excursion nautique": "Boat cruise / Excursion",
  "Ski alpin": "Downhill skiing",
  "Motoneige": "Snowmobiling",
  "Traîneau à chiens": "Dog sledding",
  "Sentiers de raquettes": "Snowshoeing trails",
  "Ski de fond": "Cross-country skiing",
  "Pêche sur glace": "Ice fishing",
  "Glissade sur tube": "Tubing",
  "Patinage / Hockey extérieur": "Skating / Outdoor hockey",
  "Fatbike": "Fat biking",
  "Cabane à sucre": "Sugar shack",
  "Magasinage (shopping)": "Shopping",
  "Musée": "Museum",
  "Restaurant / Bistro": "Restaurant / Bistro",
  "Microbrasserie": "Microbrewery",
  "Spa nordique": "Nordic spa",
  "Casino": "Casino",
  "Cinéma": "Movie theatre",
  "Village touristique": "Tourist village",
};

export function getNearbyLabel(activity: string, locale: string): string {
  if (locale !== "en") return activity;
  return NEARBY_EN[activity] ?? activity;
}
