// Données fictives pour le prototype.
(function () {

const CHALETS = [
  {
    id: 'kbn-001',
    title: 'Chalet au bord du lac Memphrémagog',
    region: 'Magog, Estrie',
    distance: 'à 1 h 30 de Montréal',
    guests: 8, beds: 4, baths: 2,
    price: 240,
    rating: 4.92, reviews: 87,
    favorite: true,
    badge: 'Coup de cœur',
    photoBg: 'linear-gradient(135deg, #2f5938 0%, #54879b 60%, #d97441 100%)',
    description: "Un refuge en bois rond pour 8 voyageurs, à 5 min à pied de la plage privée. Spa extérieur, foyer au bois, vue dégagée sur le lac Memphrémagog. Idéal pour une escapade en famille ou entre amis.",
    amenities: [
      { icon: 'waves',          label: 'Accès au lac (privé)' },
      { icon: 'flame',          label: 'Foyer au bois' },
      { icon: 'wifi',           label: 'Wi-Fi haute vitesse' },
      { icon: 'car',            label: 'Stationnement 4 voitures' },
      { icon: 'trees',          label: 'Terrain boisé 2 acres' },
      { icon: 'dog',            label: 'Animaux acceptés' },
    ],
    host: {
      name: 'Marie-Pier',
      initial: 'M',
      gradient: 'linear-gradient(135deg, #e5996b, #3d7048)',
      role: 'Hôtesse',
      since: 2021,
      verified: true,
      quote: "Un coin de paradis qu'on aime partager."
    },
    gallery: [
      'linear-gradient(135deg, #2f5938 0%, #54879b 60%, #d97441 100%)',
      'linear-gradient(135deg, #356c81 0%, #1c3622 100%)',
      'linear-gradient(135deg, #b9a482 0%, #25462c 100%)',
      'linear-gradient(135deg, #d97441 0%, #82361a 100%)',
      'linear-gradient(135deg, #88ad8f 0%, #356c81 100%)',
    ]
  },
  {
    id: 'kbn-002',
    title: 'Refuge dans la forêt',
    region: 'Mont-Tremblant, Laurentides',
    distance: 'à 1 h de Montréal',
    guests: 6, beds: 3, baths: 2,
    price: 185,
    rating: 4.87, reviews: 43,
    favorite: false,
    badge: null,
    photoBg: 'linear-gradient(135deg, #b9a482 0%, #c95a26 100%)',
  },
  {
    id: 'kbn-003',
    title: 'Cabane sur pilotis au bord du fleuve',
    region: 'Île d\'Orléans, Capitale-Nationale',
    distance: 'à 20 min de Québec',
    guests: 4, beds: 2, baths: 1,
    price: 165,
    rating: 4.95, reviews: 112,
    favorite: false,
    badge: 'Nouveau',
    photoBg: 'linear-gradient(135deg, #54879b 0%, #ebe1cf 100%)',
  },
  {
    id: 'kbn-004',
    title: 'Chalet ski-in/ski-out, vue panoramique',
    region: 'Mont-Sainte-Anne, Capitale-Nationale',
    distance: 'à 35 min de Québec',
    guests: 10, beds: 5, baths: 3,
    price: 320,
    rating: 4.89, reviews: 64,
    favorite: false,
    badge: null,
    photoBg: 'linear-gradient(135deg, #adc9d4 0%, #2f5938 100%)',
  },
  {
    id: 'kbn-005',
    title: 'Mini-chalet rustique au bord du lac',
    region: 'Saint-Donat, Lanaudière',
    distance: 'à 1 h 30 de Montréal',
    guests: 2, beds: 1, baths: 1,
    price: 125,
    rating: 4.78, reviews: 28,
    favorite: false,
    badge: null,
    photoBg: 'linear-gradient(135deg, #25462c 0%, #97825f 100%)',
  },
  {
    id: 'kbn-006',
    title: 'Maison en bois rond familiale',
    region: 'Stoneham, Capitale-Nationale',
    distance: 'à 25 min de Québec',
    guests: 12, beds: 6, baths: 4,
    price: 420,
    rating: 4.91, reviews: 156,
    favorite: true,
    badge: 'Coup de cœur',
    photoBg: 'linear-gradient(135deg, #74634a 0%, #d97441 60%, #fefcf7 100%)',
  },
  {
    id: 'kbn-007',
    title: 'Chalet en bord de rivière, spa privé',
    region: 'Wakefield, Outaouais',
    distance: 'à 30 min de Gatineau',
    guests: 6, beds: 3, baths: 2,
    price: 210,
    rating: 4.84, reviews: 51,
    favorite: false,
    badge: null,
    photoBg: 'linear-gradient(135deg, #356c81 0%, #88ad8f 100%)',
  },
  {
    id: 'kbn-008',
    title: 'Refuge nordique tout équipé',
    region: 'Saint-Sauveur, Laurentides',
    distance: 'à 45 min de Montréal',
    guests: 4, beds: 2, baths: 1,
    price: 175,
    rating: 4.93, reviews: 74,
    favorite: false,
    badge: null,
    photoBg: 'linear-gradient(135deg, #1c3622 0%, #97825f 60%, #e5996b 100%)',
  },
];

const REGIONS = [
  { id: 'all',         label: 'Tout',           icon: 'compass' },
  { id: 'lac',         label: 'Bord du lac',    icon: 'waves' },
  { id: 'foret',       label: 'Dans la forêt',  icon: 'trees' },
  { id: 'ski',         label: 'Ski-in/ski-out', icon: 'mountain-snow' },
  { id: 'spa',         label: 'Avec spa',       icon: 'flame' },
  { id: 'animaux',     label: 'Animaux ok',     icon: 'dog' },
  { id: 'vue',         label: 'Vue panoramique', icon: 'mountain' },
  { id: 'rustique',    label: 'Rustique',       icon: 'home' },
  { id: 'luxe',        label: 'Luxueux',        icon: 'sparkles' },
  { id: 'famille',     label: 'Pour familles',  icon: 'users' },
];

const REVIEWS = [
  {
    name: 'Sophie L.',
    date: 'Août 2025',
    rating: 5,
    text: "Un vrai coup de cœur. Marie-Pier est aux petits soins, le chalet est encore plus beau que sur les photos. On a passé nos soirées autour du feu. On reviendra.",
    initial: 'S',
    gradient: 'linear-gradient(135deg, #efbf9f, #356c81)',
  },
  {
    name: 'Étienne G.',
    date: 'Juillet 2025',
    rating: 5,
    text: "Calme, vue magnifique, équipement complet. Le spa au coucher de soleil sur le lac, ça vaut tous les hôtels du monde.",
    initial: 'É',
    gradient: 'linear-gradient(135deg, #88ad8f, #c95a26)',
  },
  {
    name: 'Camille &  Jean-François',
    date: 'Juin 2025',
    rating: 4,
    text: "Très bel endroit. Petit bémol sur la connexion Wi-Fi en bas, mais l'idée d'un chalet c'est aussi de débrancher. Marie-Pier répond ultra vite.",
    initial: 'C',
    gradient: 'linear-gradient(135deg, #54879b, #b9a482)',
  },
];

window.KBN_DATA = { CHALETS, REGIONS, REVIEWS };

})();
